'use strict';

const HANJA_DATA = [
  // ===== 8급 (50자) =====
  {id:"h001",level:8,char:"一",eumhun:"한 일"},{id:"h002",level:8,char:"二",eumhun:"두 이"},{id:"h003",level:8,char:"三",eumhun:"석 삼"},{id:"h004",level:8,char:"四",eumhun:"넉 사"},{id:"h005",level:8,char:"五",eumhun:"다섯 오"},
  {id:"h006",level:8,char:"六",eumhun:"여섯 육"},{id:"h007",level:8,char:"七",eumhun:"일곱 칠"},{id:"h008",level:8,char:"八",eumhun:"여덟 팔"},{id:"h009",level:8,char:"九",eumhun:"아홉 구"},{id:"h010",level:8,char:"十",eumhun:"열 십"},
  {id:"h011",level:8,char:"百",eumhun:"일백 백"},{id:"h012",level:8,char:"千",eumhun:"일천 천"},{id:"h013",level:8,char:"萬",eumhun:"일만 만"},
  {id:"h014",level:8,char:"山",eumhun:"뫼 산"},{id:"h015",level:8,char:"川",eumhun:"내 천"},{id:"h016",level:8,char:"田",eumhun:"밭 전"},{id:"h017",level:8,char:"水",eumhun:"물 수"},{id:"h018",level:8,char:"火",eumhun:"불 화"},
  {id:"h019",level:8,char:"木",eumhun:"나무 목"},{id:"h020",level:8,char:"金",eumhun:"쇠 금"},{id:"h021",level:8,char:"土",eumhun:"흙 토"},
  {id:"h022",level:8,char:"日",eumhun:"날 일"},{id:"h023",level:8,char:"月",eumhun:"달 월"},{id:"h024",level:8,char:"年",eumhun:"해 년"},
  {id:"h025",level:8,char:"天",eumhun:"하늘 천"},{id:"h026",level:8,char:"地",eumhun:"땅 지"},
  {id:"h027",level:8,char:"東",eumhun:"동녘 동"},{id:"h028",level:8,char:"西",eumhun:"서녘 서"},{id:"h029",level:8,char:"南",eumhun:"남녘 남"},{id:"h030",level:8,char:"北",eumhun:"북녘 북"},
  {id:"h031",level:8,char:"上",eumhun:"위 상"},{id:"h032",level:8,char:"下",eumhun:"아래 하"},
  {id:"h033",level:8,char:"大",eumhun:"큰 대"},{id:"h034",level:8,char:"小",eumhun:"작을 소"},{id:"h035",level:8,char:"中",eumhun:"가운데 중"},
  {id:"h036",level:8,char:"人",eumhun:"사람 인"},{id:"h037",level:8,char:"父",eumhun:"아버지 부"},{id:"h038",level:8,char:"母",eumhun:"어머니 모"},
  {id:"h039",level:8,char:"兄",eumhun:"맏 형"},{id:"h040",level:8,char:"弟",eumhun:"아우 제"},{id:"h041",level:8,char:"女",eumhun:"여자 여"},{id:"h042",level:8,char:"子",eumhun:"아들 자"},
  {id:"h043",level:8,char:"王",eumhun:"임금 왕"},{id:"h044",level:8,char:"門",eumhun:"문 문"},
  {id:"h045",level:8,char:"口",eumhun:"입 구"},{id:"h046",level:8,char:"手",eumhun:"손 수"},{id:"h047",level:8,char:"足",eumhun:"발 족"},{id:"h048",level:8,char:"耳",eumhun:"귀 이"},{id:"h049",level:8,char:"目",eumhun:"눈 목"},
  {id:"h050",level:8,char:"白",eumhun:"흰 백"},

  // ===== 7급 (100자) =====
  {id:"h051",level:7,char:"校",eumhun:"학교 교"},{id:"h052",level:7,char:"學",eumhun:"배울 학"},{id:"h053",level:7,char:"生",eumhun:"날 생"},{id:"h054",level:7,char:"先",eumhun:"먼저 선"},
  {id:"h055",level:7,char:"室",eumhun:"집 실"},{id:"h056",level:7,char:"國",eumhun:"나라 국"},{id:"h057",level:7,char:"語",eumhun:"말씀 어"},{id:"h058",level:7,char:"文",eumhun:"글월 문"},
  {id:"h059",level:7,char:"字",eumhun:"글자 자"},{id:"h060",level:7,char:"敎",eumhun:"가르칠 교"},
  {id:"h061",level:7,char:"氣",eumhun:"기운 기"},{id:"h062",level:7,char:"空",eumhun:"빌 공"},{id:"h063",level:7,char:"里",eumhun:"마을 리"},{id:"h064",level:7,char:"道",eumhun:"길 도"},
  {id:"h065",level:7,char:"車",eumhun:"수레 차"},{id:"h066",level:7,char:"食",eumhun:"밥 식"},{id:"h067",level:7,char:"時",eumhun:"때 시"},{id:"h068",level:7,char:"來",eumhun:"올 래"},
  {id:"h069",level:7,char:"名",eumhun:"이름 명"},{id:"h070",level:7,char:"色",eumhun:"빛 색"},{id:"h071",level:7,char:"林",eumhun:"수풀 림"},
  {id:"h072",level:7,char:"正",eumhun:"바를 정"},{id:"h073",level:7,char:"高",eumhun:"높을 고"},{id:"h074",level:7,char:"長",eumhun:"길 장"},
  {id:"h075",level:7,char:"少",eumhun:"적을 소"},{id:"h076",level:7,char:"老",eumhun:"늙을 노"},{id:"h077",level:7,char:"新",eumhun:"새 신"},{id:"h078",level:7,char:"多",eumhun:"많을 다"},
  {id:"h079",level:7,char:"內",eumhun:"안 내"},{id:"h080",level:7,char:"外",eumhun:"바깥 외"},{id:"h081",level:7,char:"前",eumhun:"앞 전"},{id:"h082",level:7,char:"後",eumhun:"뒤 후"},
  {id:"h083",level:7,char:"左",eumhun:"왼 좌"},{id:"h084",level:7,char:"右",eumhun:"오른 우"},
  {id:"h085",level:7,char:"男",eumhun:"사내 남"},{id:"h086",level:7,char:"出",eumhun:"날 출"},{id:"h087",level:7,char:"入",eumhun:"들 입"},
  {id:"h088",level:7,char:"力",eumhun:"힘 력"},{id:"h089",level:7,char:"心",eumhun:"마음 심"},
  {id:"h090",level:7,char:"花",eumhun:"꽃 화"},{id:"h091",level:7,char:"草",eumhun:"풀 초"},{id:"h092",level:7,char:"竹",eumhun:"대 죽"},{id:"h093",level:7,char:"石",eumhun:"돌 석"},
  {id:"h094",level:7,char:"海",eumhun:"바다 해"},{id:"h095",level:7,char:"江",eumhun:"강 강"},
  {id:"h096",level:7,char:"市",eumhun:"저자 시"},{id:"h097",level:7,char:"村",eumhun:"마을 촌"},{id:"h098",level:7,char:"家",eumhun:"집 가"},
  {id:"h099",level:7,char:"方",eumhun:"모 방"},{id:"h100",level:7,char:"分",eumhun:"나눌 분"},{id:"h101",level:7,char:"合",eumhun:"합할 합"},
  {id:"h102",level:7,char:"春",eumhun:"봄 춘"},{id:"h103",level:7,char:"夏",eumhun:"여름 하"},{id:"h104",level:7,char:"秋",eumhun:"가을 추"},{id:"h105",level:7,char:"冬",eumhun:"겨울 동"},
  {id:"h106",level:7,char:"友",eumhun:"벗 우"},{id:"h107",level:7,char:"安",eumhun:"편안 안"},
  {id:"h108",level:7,char:"問",eumhun:"물을 문"},{id:"h109",level:7,char:"答",eumhun:"대답 답"},{id:"h110",level:7,char:"話",eumhun:"말할 화"},
  {id:"h111",level:7,char:"歌",eumhun:"노래 가"},{id:"h112",level:7,char:"野",eumhun:"들 야"},
  {id:"h113",level:7,char:"自",eumhun:"스스로 자"},{id:"h114",level:7,char:"然",eumhun:"그러할 연"},
  {id:"h115",level:7,char:"音",eumhun:"소리 음"},{id:"h116",level:7,char:"樂",eumhun:"즐길 락"},
  {id:"h117",level:7,char:"動",eumhun:"움직일 동"},{id:"h118",level:7,char:"活",eumhun:"살 활"},
  {id:"h119",level:7,char:"思",eumhun:"생각할 사"},{id:"h120",level:7,char:"孝",eumhun:"효도 효"},
  {id:"h121",level:7,char:"親",eumhun:"친할 친"},{id:"h122",level:7,char:"有",eumhun:"있을 유"},{id:"h123",level:7,char:"無",eumhun:"없을 무"},
  {id:"h124",level:7,char:"工",eumhun:"장인 공"},{id:"h125",level:7,char:"立",eumhun:"설 립"},
  {id:"h126",level:7,char:"主",eumhun:"주인 주"},{id:"h127",level:7,char:"重",eumhun:"무거울 중"},
  {id:"h128",level:7,char:"光",eumhun:"빛 광"},{id:"h129",level:7,char:"平",eumhun:"평평할 평"},
  {id:"h130",level:7,char:"電",eumhun:"번개 전"},{id:"h131",level:7,char:"漢",eumhun:"한나라 한"},
  {id:"h132",level:7,char:"靑",eumhun:"푸를 청"},{id:"h133",level:7,char:"記",eumhun:"기록할 기"},
  {id:"h134",level:7,char:"算",eumhun:"셈 산"},{id:"h135",level:7,char:"數",eumhun:"셀 수"},
  {id:"h136",level:7,char:"科",eumhun:"과목 과"},{id:"h137",level:7,char:"農",eumhun:"농사 농"},
  {id:"h138",level:7,char:"社",eumhun:"모일 사"},{id:"h139",level:7,char:"共",eumhun:"함께 공"},
  {id:"h140",level:7,char:"和",eumhun:"화할 화"},{id:"h141",level:7,char:"半",eumhun:"반 반"},
  {id:"h142",level:7,char:"每",eumhun:"매양 매"},{id:"h143",level:7,char:"間",eumhun:"사이 간"},
  {id:"h144",level:7,char:"面",eumhun:"낯 면"},{id:"h145",level:7,char:"紙",eumhun:"종이 지"},
  {id:"h146",level:7,char:"書",eumhun:"글 서"},{id:"h147",level:7,char:"讀",eumhun:"읽을 독"},
  {id:"h148",level:7,char:"英",eumhun:"꽃부리 영"},{id:"h149",level:7,char:"語",eumhun:"말씀 어"},
  {id:"h150",level:7,char:"民",eumhun:"백성 민"},

  // ===== 6급 (150자) =====
  {id:"h151",level:6,char:"功",eumhun:"공 공"},{id:"h152",level:6,char:"公",eumhun:"공변될 공"},{id:"h153",level:6,char:"古",eumhun:"예 고"},{id:"h154",level:6,char:"苦",eumhun:"쓸 고"},
  {id:"h155",level:6,char:"告",eumhun:"고할 고"},{id:"h156",level:6,char:"固",eumhun:"굳을 고"},{id:"h157",level:6,char:"考",eumhun:"상고할 고"},
  {id:"h158",level:6,char:"果",eumhun:"열매 과"},{id:"h159",level:6,char:"過",eumhun:"지날 과"},{id:"h160",level:6,char:"課",eumhun:"매길 과"},
  {id:"h161",level:6,char:"交",eumhun:"사귈 교"},{id:"h162",level:6,char:"球",eumhun:"공 구"},{id:"h163",level:6,char:"近",eumhun:"가까울 근"},
  {id:"h164",level:6,char:"急",eumhun:"급할 급"},{id:"h165",level:6,char:"級",eumhun:"등급 급"},
  {id:"h166",level:6,char:"旗",eumhun:"기 기"},{id:"h167",level:6,char:"期",eumhun:"기약할 기"},{id:"h168",level:6,char:"基",eumhun:"터 기"},
  {id:"h169",level:6,char:"念",eumhun:"생각할 념"},{id:"h170",level:6,char:"農",eumhun:"농사 농"},
  {id:"h171",level:6,char:"短",eumhun:"짧을 단"},{id:"h172",level:6,char:"堂",eumhun:"집 당"},{id:"h173",level:6,char:"代",eumhun:"대신할 대"},
  {id:"h174",level:6,char:"待",eumhun:"기다릴 대"},{id:"h175",level:6,char:"對",eumhun:"대할 대"},
  {id:"h176",level:6,char:"島",eumhun:"섬 도"},{id:"h177",level:6,char:"圖",eumhun:"그림 도"},{id:"h178",level:6,char:"度",eumhun:"법도 도"},
  {id:"h179",level:6,char:"都",eumhun:"도읍 도"},{id:"h180",level:6,char:"讀",eumhun:"읽을 독"},
  {id:"h181",level:6,char:"同",eumhun:"한가지 동"},{id:"h182",level:6,char:"洞",eumhun:"골 동"},{id:"h183",level:6,char:"童",eumhun:"아이 동"},
  {id:"h184",level:6,char:"頭",eumhun:"머리 두"},{id:"h185",level:6,char:"登",eumhun:"오를 등"},
  {id:"h186",level:6,char:"等",eumhun:"무리 등"},{id:"h187",level:6,char:"落",eumhun:"떨어질 락"},
  {id:"h188",level:6,char:"路",eumhun:"길 로"},{id:"h189",level:6,char:"來",eumhun:"올 래"},
  {id:"h190",level:6,char:"良",eumhun:"어질 량"},{id:"h191",level:6,char:"旅",eumhun:"나그네 려"},
  {id:"h192",level:6,char:"禮",eumhun:"예도 례"},{id:"h193",level:6,char:"料",eumhun:"헤아릴 료"},
  {id:"h194",level:6,char:"類",eumhun:"무리 류"},{id:"h195",level:6,char:"流",eumhun:"흐를 류"},
  {id:"h196",level:6,char:"理",eumhun:"다스릴 리"},{id:"h197",level:6,char:"利",eumhun:"이로울 리"},
  {id:"h198",level:6,char:"明",eumhun:"밝을 명"},{id:"h199",level:6,char:"命",eumhun:"목숨 명"},{id:"h200",level:6,char:"目",eumhun:"눈 목"},
  {id:"h201",level:6,char:"物",eumhun:"물건 물"},{id:"h202",level:6,char:"美",eumhun:"아름다울 미"},
  {id:"h203",level:6,char:"反",eumhun:"돌이킬 반"},{id:"h204",level:6,char:"班",eumhun:"나눌 반"},{id:"h205",level:6,char:"發",eumhun:"필 발"},
  {id:"h206",level:6,char:"放",eumhun:"놓을 방"},{id:"h207",level:6,char:"番",eumhun:"차례 번"},
  {id:"h208",level:6,char:"別",eumhun:"나눌 별"},{id:"h209",level:6,char:"病",eumhun:"병 병"},
  {id:"h210",level:6,char:"服",eumhun:"옷 복"},{id:"h211",level:6,char:"本",eumhun:"근본 본"},
  {id:"h212",level:6,char:"部",eumhun:"떼 부"},{id:"h213",level:6,char:"不",eumhun:"아닐 불"},
  {id:"h214",level:6,char:"事",eumhun:"일 사"},{id:"h215",level:6,char:"使",eumhun:"부릴 사"},
  {id:"h216",level:6,char:"死",eumhun:"죽을 사"},{id:"h217",level:6,char:"山",eumhun:"뫼 산"},
  {id:"h218",level:6,char:"上",eumhun:"위 상"},{id:"h219",level:6,char:"商",eumhun:"장사 상"},
  {id:"h220",level:6,char:"色",eumhun:"빛 색"},{id:"h221",level:6,char:"西",eumhun:"서녘 서"},
  {id:"h222",level:6,char:"線",eumhun:"줄 선"},{id:"h223",level:6,char:"雪",eumhun:"눈 설"},
  {id:"h224",level:6,char:"成",eumhun:"이룰 성"},{id:"h225",level:6,char:"世",eumhun:"인간 세"},
  {id:"h226",level:6,char:"所",eumhun:"바 소"},{id:"h227",level:6,char:"速",eumhun:"빠를 속"},
  {id:"h228",level:6,char:"送",eumhun:"보낼 송"},{id:"h229",level:6,char:"受",eumhun:"받을 수"},
  {id:"h230",level:6,char:"手",eumhun:"손 수"},{id:"h231",level:6,char:"習",eumhun:"익힐 습"},
  {id:"h232",level:6,char:"勝",eumhun:"이길 승"},{id:"h233",level:6,char:"始",eumhun:"비로소 시"},
  {id:"h234",level:6,char:"身",eumhun:"몸 신"},{id:"h235",level:6,char:"信",eumhun:"믿을 신"},
  {id:"h236",level:6,char:"失",eumhun:"잃을 실"},{id:"h237",level:6,char:"心",eumhun:"마음 심"},
  {id:"h238",level:6,char:"愛",eumhun:"사랑 애"},{id:"h239",level:6,char:"夜",eumhun:"밤 야"},
  {id:"h240",level:6,char:"藥",eumhun:"약 약"},{id:"h241",level:6,char:"弱",eumhun:"약할 약"},
  {id:"h242",level:6,char:"言",eumhun:"말씀 언"},{id:"h243",level:6,char:"業",eumhun:"업 업"},
  {id:"h244",level:6,char:"然",eumhun:"그러할 연"},{id:"h245",level:6,char:"永",eumhun:"길 영"},
  {id:"h246",level:6,char:"完",eumhun:"완전할 완"},{id:"h247",level:6,char:"用",eumhun:"쓸 용"},
  {id:"h248",level:6,char:"雨",eumhun:"비 우"},{id:"h249",level:6,char:"原",eumhun:"근원 원"},
  {id:"h250",level:6,char:"遠",eumhun:"멀 원"},{id:"h251",level:6,char:"月",eumhun:"달 월"},
  {id:"h252",level:6,char:"位",eumhun:"자리 위"},{id:"h253",level:6,char:"由",eumhun:"말미암을 유"},
  {id:"h254",level:6,char:"育",eumhun:"기를 육"},{id:"h255",level:6,char:"意",eumhun:"뜻 의"},
  {id:"h256",level:6,char:"理",eumhun:"다스릴 리"},{id:"h257",level:6,char:"人",eumhun:"사람 인"},
  {id:"h258",level:6,char:"日",eumhun:"날 일"},{id:"h259",level:6,char:"作",eumhun:"지을 작"},
  {id:"h260",level:6,char:"場",eumhun:"마당 장"},{id:"h261",level:6,char:"全",eumhun:"온전 전"},
  {id:"h262",level:6,char:"戰",eumhun:"싸울 전"},{id:"h263",level:6,char:"庭",eumhun:"뜰 정"},
  {id:"h264",level:6,char:"定",eumhun:"정할 정"},{id:"h265",level:6,char:"祭",eumhun:"제사 제"},
  {id:"h266",level:6,char:"題",eumhun:"제목 제"},{id:"h267",level:6,char:"族",eumhun:"겨레 족"},
  {id:"h268",level:6,char:"注",eumhun:"부을 주"},{id:"h269",level:6,char:"週",eumhun:"주일 주"},
  {id:"h270",level:6,char:"中",eumhun:"가운데 중"},{id:"h271",level:6,char:"地",eumhun:"땅 지"},
  {id:"h272",level:6,char:"紙",eumhun:"종이 지"},{id:"h273",level:6,char:"直",eumhun:"곧을 직"},
  {id:"h274",level:6,char:"集",eumhun:"모을 집"},{id:"h275",level:6,char:"窓",eumhun:"창 창"},
  {id:"h276",level:6,char:"體",eumhun:"몸 체"},{id:"h277",level:6,char:"初",eumhun:"처음 초"},
  {id:"h278",level:6,char:"草",eumhun:"풀 초"},{id:"h279",level:6,char:"總",eumhun:"다 총"},
  {id:"h280",level:6,char:"村",eumhun:"마을 촌"},{id:"h281",level:6,char:"最",eumhun:"가장 최"},
  {id:"h282",level:6,char:"出",eumhun:"날 출"},{id:"h283",level:6,char:"春",eumhun:"봄 춘"},
  {id:"h284",level:6,char:"層",eumhun:"층 층"},{id:"h285",level:6,char:"快",eumhun:"쾌할 쾌"},
  {id:"h286",level:6,char:"特",eumhun:"특별할 특"},{id:"h287",level:6,char:"風",eumhun:"바람 풍"},
  {id:"h288",level:6,char:"必",eumhun:"반드시 필"},{id:"h289",level:6,char:"漢",eumhun:"한나라 한"},
  {id:"h290",level:6,char:"海",eumhun:"바다 해"},{id:"h291",level:6,char:"幸",eumhun:"다행 행"},
  {id:"h292",level:6,char:"向",eumhun:"향할 향"},{id:"h293",level:6,char:"現",eumhun:"나타날 현"},
  {id:"h294",level:6,char:"形",eumhun:"모양 형"},{id:"h295",level:6,char:"號",eumhun:"이름 호"},
  {id:"h296",level:6,char:"花",eumhun:"꽃 화"},{id:"h297",level:6,char:"話",eumhun:"말할 화"},
  {id:"h298",level:6,char:"活",eumhun:"살 활"},{id:"h299",level:6,char:"孝",eumhun:"효도 효"},
  {id:"h300",level:6,char:"後",eumhun:"뒤 후"},

  // ===== 5급 (200자) =====
  {id:"h301",level:5,char:"加",eumhun:"더할 가"},{id:"h302",level:5,char:"假",eumhun:"거짓 가"},{id:"h303",level:5,char:"各",eumhun:"각각 각"},
  {id:"h304",level:5,char:"感",eumhun:"느낄 감"},{id:"h305",level:5,char:"甲",eumhun:"갑옷 갑"},{id:"h306",level:5,char:"講",eumhun:"외울 강"},
  {id:"h307",level:5,char:"強",eumhun:"강할 강"},{id:"h308",level:5,char:"改",eumhun:"고칠 개"},{id:"h309",level:5,char:"客",eumhun:"손 객"},
  {id:"h310",level:5,char:"格",eumhun:"격식 격"},{id:"h311",level:5,char:"決",eumhun:"결단할 결"},{id:"h312",level:5,char:"結",eumhun:"맺을 결"},
  {id:"h313",level:5,char:"敬",eumhun:"공경할 경"},{id:"h314",level:5,char:"景",eumhun:"볕 경"},{id:"h315",level:5,char:"競",eumhun:"다툴 경"},
  {id:"h316",level:5,char:"係",eumhun:"맬 계"},{id:"h317",level:5,char:"界",eumhun:"지경 계"},{id:"h318",level:5,char:"計",eumhun:"셈할 계"},
  {id:"h319",level:5,char:"係",eumhun:"맬 계"},{id:"h320",level:5,char:"高",eumhun:"높을 고"},
  {id:"h321",level:5,char:"骨",eumhun:"뼈 골"},{id:"h322",level:5,char:"觀",eumhun:"볼 관"},{id:"h323",level:5,char:"官",eumhun:"벼슬 관"},
  {id:"h324",level:5,char:"關",eumhun:"빗장 관"},{id:"h325",level:5,char:"敎",eumhun:"가르칠 교"},
  {id:"h326",level:5,char:"求",eumhun:"구할 구"},{id:"h327",level:5,char:"究",eumhun:"궁구할 구"},{id:"h328",level:5,char:"國",eumhun:"나라 국"},
  {id:"h329",level:5,char:"軍",eumhun:"군사 군"},{id:"h330",level:5,char:"宮",eumhun:"집 궁"},
  {id:"h331",level:5,char:"規",eumhun:"법 규"},{id:"h332",level:5,char:"根",eumhun:"뿌리 근"},
  {id:"h333",level:5,char:"今",eumhun:"이제 금"},{id:"h334",level:5,char:"禁",eumhun:"금할 금"},
  {id:"h335",level:5,char:"記",eumhun:"기록할 기"},{id:"h336",level:5,char:"技",eumhun:"재주 기"},
  {id:"h337",level:5,char:"吉",eumhun:"길할 길"},{id:"h338",level:5,char:"納",eumhun:"들일 납"},
  {id:"h339",level:5,char:"能",eumhun:"능할 능"},{id:"h340",level:5,char:"多",eumhun:"많을 다"},
  {id:"h341",level:5,char:"團",eumhun:"둥글 단"},{id:"h342",level:5,char:"壇",eumhun:"단 단"},
  {id:"h343",level:5,char:"達",eumhun:"통달할 달"},{id:"h344",level:5,char:"談",eumhun:"말씀 담"},
  {id:"h345",level:5,char:"當",eumhun:"마땅할 당"},{id:"h346",level:5,char:"大",eumhun:"큰 대"},
  {id:"h347",level:5,char:"德",eumhun:"큰 덕"},{id:"h348",level:5,char:"道",eumhun:"길 도"},
  {id:"h349",level:5,char:"讀",eumhun:"읽을 독"},{id:"h350",level:5,char:"獨",eumhun:"홀로 독"},
  {id:"h351",level:5,char:"頭",eumhun:"머리 두"},{id:"h352",level:5,char:"得",eumhun:"얻을 득"},
  {id:"h353",level:5,char:"等",eumhun:"무리 등"},{id:"h354",level:5,char:"力",eumhun:"힘 력"},
  {id:"h355",level:5,char:"歷",eumhun:"지낼 력"},{id:"h356",level:5,char:"連",eumhun:"잇닿을 련"},
  {id:"h357",level:5,char:"列",eumhun:"벌일 렬"},{id:"h358",level:5,char:"領",eumhun:"거느릴 령"},
  {id:"h359",level:5,char:"例",eumhun:"법식 례"},{id:"h360",level:5,char:"老",eumhun:"늙을 로"},
  {id:"h361",level:5,char:"論",eumhun:"의논할 론"},{id:"h362",level:5,char:"末",eumhun:"끝 말"},
  {id:"h363",level:5,char:"望",eumhun:"바랄 망"},{id:"h364",level:5,char:"亡",eumhun:"망할 망"},
  {id:"h365",level:5,char:"每",eumhun:"매양 매"},{id:"h366",level:5,char:"賣",eumhun:"팔 매"},
  {id:"h367",level:5,char:"買",eumhun:"살 매"},{id:"h368",level:5,char:"名",eumhun:"이름 명"},
  {id:"h369",level:5,char:"目",eumhun:"눈 목"},{id:"h370",level:5,char:"文",eumhun:"글월 문"},
  {id:"h371",level:5,char:"聞",eumhun:"들을 문"},{id:"h372",level:5,char:"問",eumhun:"물을 문"},
  {id:"h373",level:5,char:"班",eumhun:"나눌 반"},{id:"h374",level:5,char:"方",eumhun:"모 방"},
  {id:"h375",level:5,char:"放",eumhun:"놓을 방"},{id:"h376",level:5,char:"背",eumhun:"등 배"},
  {id:"h377",level:5,char:"倍",eumhun:"곱 배"},{id:"h378",level:5,char:"白",eumhun:"흰 백"},
  {id:"h379",level:5,char:"法",eumhun:"법 법"},{id:"h380",level:5,char:"變",eumhun:"변할 변"},
  {id:"h381",level:5,char:"保",eumhun:"보전할 보"},{id:"h382",level:5,char:"報",eumhun:"갚을 보"},
  {id:"h383",level:5,char:"分",eumhun:"나눌 분"},{id:"h384",level:5,char:"比",eumhun:"견줄 비"},
  {id:"h385",level:5,char:"費",eumhun:"쓸 비"},{id:"h386",level:5,char:"四",eumhun:"넉 사"},
  {id:"h387",level:5,char:"史",eumhun:"역사 사"},{id:"h388",level:5,char:"産",eumhun:"낳을 산"},
  {id:"h389",level:5,char:"省",eumhun:"살필 성"},{id:"h390",level:5,char:"性",eumhun:"성품 성"},
  {id:"h391",level:5,char:"細",eumhun:"가늘 세"},{id:"h392",level:5,char:"術",eumhun:"재주 술"},
  {id:"h393",level:5,char:"勝",eumhun:"이길 승"},{id:"h394",level:5,char:"植",eumhun:"심을 식"},
  {id:"h395",level:5,char:"深",eumhun:"깊을 심"},{id:"h396",level:5,char:"案",eumhun:"책상 안"},
  {id:"h397",level:5,char:"約",eumhun:"맺을 약"},{id:"h398",level:5,char:"洋",eumhun:"큰바다 양"},
  {id:"h399",level:5,char:"魚",eumhun:"물고기 어"},{id:"h400",level:5,char:"億",eumhun:"억 억"},
  {id:"h401",level:5,char:"研",eumhun:"갈 연"},{id:"h402",level:5,char:"演",eumhun:"흐를 연"},
  {id:"h403",level:5,char:"熱",eumhun:"더울 열"},{id:"h404",level:5,char:"英",eumhun:"꽃부리 영"},
  {id:"h405",level:5,char:"溫",eumhun:"따뜻할 온"},{id:"h406",level:5,char:"王",eumhun:"임금 왕"},
  {id:"h407",level:5,char:"要",eumhun:"구할 요"},{id:"h408",level:5,char:"友",eumhun:"벗 우"},
  {id:"h409",level:5,char:"元",eumhun:"으뜸 원"},{id:"h410",level:5,char:"院",eumhun:"집 원"},
  {id:"h411",level:5,char:"音",eumhun:"소리 음"},{id:"h412",level:5,char:"衣",eumhun:"옷 의"},
  {id:"h413",level:5,char:"醫",eumhun:"의원 의"},{id:"h414",level:5,char:"人",eumhun:"사람 인"},
  {id:"h415",level:5,char:"認",eumhun:"알 인"},{id:"h416",level:5,char:"子",eumhun:"아들 자"},
  {id:"h417",level:5,char:"者",eumhun:"놈 자"},{id:"h418",level:5,char:"章",eumhun:"글 장"},
  {id:"h419",level:5,char:"財",eumhun:"재물 재"},{id:"h420",level:5,char:"才",eumhun:"재주 재"},
  {id:"h421",level:5,char:"低",eumhun:"낮을 저"},{id:"h422",level:5,char:"敵",eumhun:"원수 적"},
  {id:"h423",level:5,char:"積",eumhun:"쌓을 적"},{id:"h424",level:5,char:"的",eumhun:"과녁 적"},
  {id:"h425",level:5,char:"展",eumhun:"펼 전"},{id:"h426",level:5,char:"節",eumhun:"마디 절"},
  {id:"h427",level:5,char:"政",eumhun:"정사 정"},{id:"h428",level:5,char:"精",eumhun:"정할 정"},
  {id:"h429",level:5,char:"整",eumhun:"가지런할 정"},{id:"h430",level:5,char:"際",eumhun:"사이 제"},
  {id:"h431",level:5,char:"第",eumhun:"차례 제"},{id:"h432",level:5,char:"制",eumhun:"억제할 제"},
  {id:"h433",level:5,char:"組",eumhun:"짤 조"},{id:"h434",level:5,char:"存",eumhun:"있을 존"},
  {id:"h435",level:5,char:"宗",eumhun:"마루 종"},{id:"h436",level:5,char:"種",eumhun:"씨 종"},
  {id:"h437",level:5,char:"座",eumhun:"앉을 좌"},{id:"h438",level:5,char:"罪",eumhun:"허물 죄"},
  {id:"h439",level:5,char:"住",eumhun:"살 주"},{id:"h440",level:5,char:"準",eumhun:"준할 준"},
  {id:"h441",level:5,char:"增",eumhun:"더할 증"},{id:"h442",level:5,char:"知",eumhun:"알 지"},
  {id:"h443",level:5,char:"進",eumhun:"나아갈 진"},{id:"h444",level:5,char:"質",eumhun:"바탕 질"},
  {id:"h445",level:5,char:"着",eumhun:"붙을 착"},{id:"h446",level:5,char:"創",eumhun:"비롯할 창"},
  {id:"h447",level:5,char:"清",eumhun:"맑을 청"},{id:"h448",level:5,char:"請",eumhun:"청할 청"},
  {id:"h449",level:5,char:"聽",eumhun:"들을 청"},{id:"h450",level:5,char:"治",eumhun:"다스릴 치"},
  {id:"h451",level:5,char:"齒",eumhun:"이 치"},{id:"h452",level:5,char:"他",eumhun:"다를 타"},
  {id:"h453",level:5,char:"太",eumhun:"클 태"},{id:"h454",level:5,char:"通",eumhun:"통할 통"},
  {id:"h455",level:5,char:"判",eumhun:"판단할 판"},{id:"h456",level:5,char:"敗",eumhun:"패할 패"},
  {id:"h457",level:5,char:"品",eumhun:"물건 품"},{id:"h458",level:5,char:"合",eumhun:"합할 합"},
  {id:"h459",level:5,char:"港",eumhun:"항구 항"},{id:"h460",level:5,char:"行",eumhun:"다닐 행"},
  {id:"h461",level:5,char:"況",eumhun:"하물며 황"},{id:"h462",level:5,char:"會",eumhun:"모일 회"},
  {id:"h463",level:5,char:"效",eumhun:"본받을 효"},{id:"h464",level:5,char:"訓",eumhun:"가르칠 훈"},
  {id:"h465",level:5,char:"休",eumhun:"쉴 휴"},{id:"h466",level:5,char:"希",eumhun:"바랄 희"},

  // ===== 4급 (300자) =====
  {id:"h467",level:4,char:"價",eumhun:"값 가"},{id:"h468",level:4,char:"可",eumhun:"옳을 가"},{id:"h469",level:4,char:"街",eumhun:"거리 가"},
  {id:"h470",level:4,char:"刻",eumhun:"새길 각"},{id:"h471",level:4,char:"看",eumhun:"볼 간"},{id:"h472",level:4,char:"幹",eumhun:"줄기 간"},
  {id:"h473",level:4,char:"減",eumhun:"덜 감"},{id:"h474",level:4,char:"監",eumhun:"볼 감"},{id:"h475",level:4,char:"鑑",eumhun:"거울 감"},
  {id:"h476",level:4,char:"康",eumhun:"편안 강"},{id:"h477",level:4,char:"慨",eumhun:"슬퍼할 개"},{id:"h478",level:4,char:"槪",eumhun:"대개 개"},
  {id:"h479",level:4,char:"建",eumhun:"세울 건"},{id:"h480",level:4,char:"健",eumhun:"굳셀 건"},{id:"h481",level:4,char:"儉",eumhun:"검소할 검"},
  {id:"h482",level:4,char:"見",eumhun:"볼 견"},{id:"h483",level:4,char:"缺",eumhun:"이지러질 결"},{id:"h484",level:4,char:"兼",eumhun:"겸할 겸"},
  {id:"h485",level:4,char:"謙",eumhun:"겸손할 겸"},{id:"h486",level:4,char:"境",eumhun:"지경 경"},{id:"h487",level:4,char:"警",eumhun:"경계할 경"},
  {id:"h488",level:4,char:"經",eumhun:"지날 경"},{id:"h489",level:4,char:"輕",eumhun:"가벼울 경"},{id:"h490",level:4,char:"繼",eumhun:"이을 계"},
  {id:"h491",level:4,char:"故",eumhun:"연고 고"},{id:"h492",level:4,char:"困",eumhun:"곤할 곤"},{id:"h493",level:4,char:"骨",eumhun:"뼈 골"},
  {id:"h494",level:4,char:"共",eumhun:"함께 공"},{id:"h495",level:4,char:"供",eumhun:"이바지할 공"},{id:"h496",level:4,char:"攻",eumhun:"칠 공"},
  {id:"h497",level:4,char:"誇",eumhun:"자랑할 과"},{id:"h498",level:4,char:"廣",eumhun:"넓을 광"},{id:"h499",level:4,char:"橋",eumhun:"다리 교"},
  {id:"h500",level:4,char:"校",eumhun:"학교 교"},{id:"h501",level:4,char:"構",eumhun:"얽을 구"},{id:"h502",level:4,char:"貴",eumhun:"귀할 귀"},
  {id:"h503",level:4,char:"均",eumhun:"고를 균"},{id:"h504",level:4,char:"極",eumhun:"극진할 극"},{id:"h505",level:4,char:"勤",eumhun:"부지런할 근"},
  {id:"h506",level:4,char:"謹",eumhun:"삼갈 근"},{id:"h507",level:4,char:"錦",eumhun:"비단 금"},{id:"h508",level:4,char:"給",eumhun:"줄 급"},
  {id:"h509",level:4,char:"機",eumhun:"틀 기"},{id:"h510",level:4,char:"氣",eumhun:"기운 기"},{id:"h511",level:4,char:"旣",eumhun:"이미 기"},
  {id:"h512",level:4,char:"難",eumhun:"어려울 난"},{id:"h513",level:4,char:"暖",eumhun:"따뜻할 난"},{id:"h514",level:4,char:"內",eumhun:"안 내"},
  {id:"h515",level:4,char:"努",eumhun:"힘쓸 노"},{id:"h516",level:4,char:"怒",eumhun:"성낼 노"},{id:"h517",level:4,char:"農",eumhun:"농사 농"},
  {id:"h518",level:4,char:"斷",eumhun:"끊을 단"},{id:"h519",level:4,char:"擔",eumhun:"멜 담"},{id:"h520",level:4,char:"黨",eumhun:"무리 당"},
  {id:"h521",level:4,char:"大",eumhun:"큰 대"},{id:"h522",level:4,char:"帶",eumhun:"띠 대"},{id:"h523",level:4,char:"導",eumhun:"이끌 도"},
  {id:"h524",level:4,char:"獨",eumhun:"홀로 독"},{id:"h525",level:4,char:"墮",eumhun:"떨어질 타"},{id:"h526",level:4,char:"落",eumhun:"떨어질 락"},
  {id:"h527",level:4,char:"亂",eumhun:"어지러울 란"},{id:"h528",level:4,char:"朗",eumhun:"밝을 랑"},{id:"h529",level:4,char:"量",eumhun:"헤아릴 량"},
  {id:"h530",level:4,char:"慮",eumhun:"생각할 려"},{id:"h531",level:4,char:"力",eumhun:"힘 력"},{id:"h532",level:4,char:"戀",eumhun:"사모할 련"},
  {id:"h533",level:4,char:"廉",eumhun:"청렴할 렴"},{id:"h534",level:4,char:"令",eumhun:"명령할 령"},{id:"h535",level:4,char:"勞",eumhun:"일할 로"},
  {id:"h536",level:4,char:"律",eumhun:"법 률"},{id:"h537",level:4,char:"臨",eumhun:"임할 림"},{id:"h538",level:4,char:"滿",eumhun:"찰 만"},
  {id:"h539",level:4,char:"亡",eumhun:"망할 망"},{id:"h540",level:4,char:"茂",eumhun:"무성할 무"},{id:"h541",level:4,char:"務",eumhun:"힘쓸 무"},
  {id:"h542",level:4,char:"密",eumhun:"빽빽할 밀"},{id:"h543",level:4,char:"博",eumhun:"넓을 박"},{id:"h544",level:4,char:"班",eumhun:"나눌 반"},
  {id:"h545",level:4,char:"伴",eumhun:"짝 반"},{id:"h546",level:4,char:"房",eumhun:"방 방"},{id:"h547",level:4,char:"防",eumhun:"막을 방"},
  {id:"h548",level:4,char:"拜",eumhun:"절 배"},{id:"h549",level:4,char:"凡",eumhun:"무릇 범"},{id:"h550",level:4,char:"辯",eumhun:"말씀 변"},
  {id:"h551",level:4,char:"福",eumhun:"복 복"},{id:"h552",level:4,char:"奉",eumhun:"받들 봉"},{id:"h553",level:4,char:"府",eumhun:"마을 부"},
  {id:"h554",level:4,char:"副",eumhun:"버금 부"},{id:"h555",level:4,char:"負",eumhun:"질 부"},{id:"h556",level:4,char:"北",eumhun:"북녘 북"},
  {id:"h557",level:4,char:"非",eumhun:"아닐 비"},{id:"h558",level:4,char:"批",eumhun:"칠 비"},{id:"h559",level:4,char:"氷",eumhun:"얼음 빙"},
  {id:"h560",level:4,char:"師",eumhun:"스승 사"},{id:"h561",level:4,char:"賜",eumhun:"줄 사"},{id:"h562",level:4,char:"散",eumhun:"흩어질 산"},
  {id:"h563",level:4,char:"殺",eumhun:"죽일 살"},{id:"h564",level:4,char:"狀",eumhun:"모양 상"},{id:"h565",level:4,char:"想",eumhun:"생각할 상"},
  {id:"h566",level:4,char:"相",eumhun:"서로 상"},{id:"h567",level:4,char:"象",eumhun:"코끼리 상"},{id:"h568",level:4,char:"署",eumhun:"서명할 서"},
  {id:"h569",level:4,char:"序",eumhun:"차례 서"},{id:"h570",level:4,char:"鮮",eumhun:"고울 선"},{id:"h571",level:4,char:"善",eumhun:"착할 선"},
  {id:"h572",level:4,char:"選",eumhun:"가릴 선"},{id:"h573",level:4,char:"誠",eumhun:"정성 성"},{id:"h574",level:4,char:"勢",eumhun:"기세 세"},
  {id:"h575",level:4,char:"素",eumhun:"흴 소"},{id:"h576",level:4,char:"損",eumhun:"덜 손"},{id:"h577",level:4,char:"首",eumhun:"머리 수"},
  {id:"h578",level:4,char:"純",eumhun:"순수할 순"},{id:"h579",level:4,char:"崇",eumhun:"높을 숭"},{id:"h580",level:4,char:"乘",eumhun:"탈 승"},
  {id:"h581",level:4,char:"施",eumhun:"베풀 시"},{id:"h582",level:4,char:"識",eumhun:"알 식"},{id:"h583",level:4,char:"申",eumhun:"펼 신"},
  {id:"h584",level:4,char:"神",eumhun:"귀신 신"},{id:"h585",level:4,char:"實",eumhun:"열매 실"},{id:"h586",level:4,char:"兒",eumhun:"아이 아"},
  {id:"h587",level:4,char:"握",eumhun:"쥘 악"},{id:"h588",level:4,char:"悅",eumhun:"기쁠 열"},{id:"h589",level:4,char:"嚴",eumhun:"엄할 엄"},
  {id:"h590",level:4,char:"餘",eumhun:"남을 여"},{id:"h591",level:4,char:"域",eumhun:"지경 역"},{id:"h592",level:4,char:"易",eumhun:"바꿀 역"},
  {id:"h593",level:4,char:"延",eumhun:"늘일 연"},{id:"h594",level:4,char:"燃",eumhun:"불탈 연"},{id:"h595",level:4,char:"影",eumhun:"그림자 영"},
  {id:"h596",level:4,char:"誤",eumhun:"그릇 오"},{id:"h597",level:4,char:"汚",eumhun:"더러울 오"},{id:"h598",level:4,char:"完",eumhun:"완전할 완"},
  {id:"h599",level:4,char:"往",eumhun:"갈 왕"},{id:"h600",level:4,char:"外",eumhun:"바깥 외"},
  {id:"h601",level:4,char:"容",eumhun:"용납할 용"},{id:"h602",level:4,char:"勇",eumhun:"날랠 용"},{id:"h603",level:4,char:"優",eumhun:"넉넉할 우"},
  {id:"h604",level:4,char:"宇",eumhun:"집 우"},{id:"h605",level:4,char:"援",eumhun:"도울 원"},{id:"h606",level:4,char:"危",eumhun:"위태할 위"},
  {id:"h607",level:4,char:"威",eumhun:"위엄 위"},{id:"h608",level:4,char:"依",eumhun:"의지할 의"},{id:"h609",level:4,char:"議",eumhun:"의논할 의"},
  {id:"h610",level:4,char:"移",eumhun:"옮길 이"},{id:"h611",level:4,char:"忍",eumhun:"참을 인"},{id:"h612",level:4,char:"因",eumhun:"인할 인"},
  {id:"h613",level:4,char:"任",eumhun:"맡길 임"},{id:"h614",level:4,char:"賃",eumhun:"품삯 임"},{id:"h615",level:4,char:"資",eumhun:"재물 자"},
  {id:"h616",level:4,char:"장",eumhun:"장수 장"},{id:"h617",level:4,char:"將",eumhun:"장수 장"},{id:"h618",level:4,char:"藏",eumhun:"감출 장"},
  {id:"h619",level:4,char:"載",eumhun:"실을 재"},{id:"h620",level:4,char:"爭",eumhun:"다툴 쟁"},{id:"h621",level:4,char:"貯",eumhun:"쌓을 저"},
  {id:"h622",level:4,char:"跡",eumhun:"발자취 적"},{id:"h623",level:4,char:"點",eumhun:"점 점"},{id:"h624",level:4,char:"靜",eumhun:"고요할 정"},
  {id:"h625",level:4,char:"情",eumhun:"뜻 정"},{id:"h626",level:4,char:"濟",eumhun:"건널 제"},{id:"h627",level:4,char:"助",eumhun:"도울 조"},
  {id:"h628",level:4,char:"早",eumhun:"이를 조"},{id:"h629",level:4,char:"調",eumhun:"고를 조"},{id:"h630",level:4,char:"造",eumhun:"지을 조"},
  {id:"h631",level:4,char:"卒",eumhun:"마칠 졸"},{id:"h632",level:4,char:"左",eumhun:"왼 좌"},{id:"h633",level:4,char:"尊",eumhun:"높을 존"},
  {id:"h634",level:4,char:"終",eumhun:"마칠 종"},{id:"h635",level:4,char:"支",eumhun:"지탱할 지"},{id:"h636",level:4,char:"智",eumhun:"슬기 지"},
  {id:"h637",level:4,char:"至",eumhun:"이를 지"},{id:"h638",level:4,char:"職",eumhun:"직분 직"},{id:"h639",level:4,char:"眞",eumhun:"참 진"},
  {id:"h640",level:4,char:"差",eumhun:"다를 차"},{id:"h641",level:4,char:"借",eumhun:"빌릴 차"},{id:"h642",level:4,char:"察",eumhun:"살필 찰"},
  {id:"h643",level:4,char:"責",eumhun:"꾸짖을 책"},{id:"h644",level:4,char:"寸",eumhun:"마디 촌"},{id:"h645",level:4,char:"推",eumhun:"밀 추"},
  {id:"h646",level:4,char:"縮",eumhun:"줄어들 축"},{id:"h647",level:4,char:"就",eumhun:"이룰 취"},{id:"h648",level:4,char:"趣",eumhun:"뜻 취"},
  {id:"h649",level:4,char:"側",eumhun:"곁 측"},{id:"h650",level:4,char:"態",eumhun:"모양 태"},{id:"h651",level:4,char:"澤",eumhun:"못 택"},
  {id:"h652",level:4,char:"討",eumhun:"칠 토"},{id:"h653",level:4,char:"透",eumhun:"사무칠 투"},{id:"h654",level:4,char:"派",eumhun:"갈래 파"},
  {id:"h655",level:4,char:"破",eumhun:"깨뜨릴 파"},{id:"h656",level:4,char:"敗",eumhun:"패할 패"},{id:"h657",level:4,char:"便",eumhun:"편할 편"},
  {id:"h658",level:4,char:"評",eumhun:"평할 평"},{id:"h659",level:4,char:"布",eumhun:"베 포"},{id:"h660",level:4,char:"被",eumhun:"입을 피"},
  {id:"h661",level:4,char:"河",eumhun:"강 하"},{id:"h662",level:4,char:"限",eumhun:"한할 한"},{id:"h663",level:4,char:"閑",eumhun:"한가할 한"},
  {id:"h664",level:4,char:"含",eumhun:"머금을 함"},{id:"h665",level:4,char:"害",eumhun:"해칠 해"},{id:"h666",level:4,char:"解",eumhun:"풀 해"},
  {id:"h667",level:4,char:"驗",eumhun:"시험 험"},{id:"h668",level:4,char:"協",eumhun:"화합할 협"},{id:"h669",level:4,char:"惠",eumhun:"은혜 혜"},
  {id:"h670",level:4,char:"呼",eumhun:"부를 호"},{id:"h671",level:4,char:"好",eumhun:"좋을 호"},{id:"h672",level:4,char:"混",eumhun:"섞일 혼"},
  {id:"h673",level:4,char:"弘",eumhun:"클 홍"},{id:"h674",level:4,char:"化",eumhun:"될 화"},{id:"h675",level:4,char:"確",eumhun:"굳을 확"},
  {id:"h676",level:4,char:"歡",eumhun:"기쁠 환"},{id:"h677",level:4,char:"患",eumhun:"근심 환"},{id:"h678",level:4,char:"回",eumhun:"돌아올 회"},
  {id:"h679",level:4,char:"獲",eumhun:"얻을 획"},{id:"h680",level:4,char:"揮",eumhun:"휘두를 휘"},{id:"h681",level:4,char:"興",eumhun:"흥할 흥"},

  // ===== 3급 (대표 300자) =====
  {id:"h682",level:3,char:"假",eumhun:"거짓 가"},{id:"h683",level:3,char:"架",eumhun:"시렁 가"},{id:"h684",level:3,char:"嫁",eumhun:"시집갈 가"},
  {id:"h685",level:3,char:"覺",eumhun:"깨달을 각"},{id:"h686",level:3,char:"脚",eumhun:"다리 각"},{id:"h687",level:3,char:"刊",eumhun:"새길 간"},
  {id:"h688",level:3,char:"簡",eumhun:"대쪽 간"},{id:"h689",level:3,char:"渴",eumhun:"목마를 갈"},{id:"h690",level:3,char:"鑑",eumhun:"거울 감"},
  {id:"h691",level:3,char:"甲",eumhun:"갑옷 갑"},{id:"h692",level:3,char:"岡",eumhun:"산등성이 강"},{id:"h693",level:3,char:"皆",eumhun:"다 개"},
  {id:"h694",level:3,char:"個",eumhun:"낱 개"},{id:"h695",level:3,char:"距",eumhun:"떨어질 거"},{id:"h696",level:3,char:"擧",eumhun:"들 거"},
  {id:"h697",level:3,char:"劍",eumhun:"칼 검"},{id:"h698",level:3,char:"激",eumhun:"격할 격"},{id:"h699",level:3,char:"隔",eumhun:"사이뜰 격"},
  {id:"h700",level:3,char:"堅",eumhun:"굳을 견"},{id:"h701",level:3,char:"肩",eumhun:"어깨 견"},{id:"h702",level:3,char:"遣",eumhun:"보낼 견"},
  {id:"h703",level:3,char:"傾",eumhun:"기울 경"},{id:"h704",level:3,char:"計",eumhun:"셈할 계"},{id:"h705",level:3,char:"鷄",eumhun:"닭 계"},
  {id:"h706",level:3,char:"姑",eumhun:"시어미 고"},{id:"h707",level:3,char:"孤",eumhun:"외로울 고"},{id:"h708",level:3,char:"穀",eumhun:"곡식 곡"},
  {id:"h709",level:3,char:"哭",eumhun:"울 곡"},{id:"h710",level:3,char:"崑",eumhun:"곤륜산 곤"},{id:"h711",level:3,char:"恭",eumhun:"공손할 공"},
  {id:"h712",level:3,char:"恐",eumhun:"두려울 공"},{id:"h713",level:3,char:"館",eumhun:"집 관"},{id:"h714",level:3,char:"慣",eumhun:"익숙할 관"},
  {id:"h715",level:3,char:"鑛",eumhun:"쇳돌 광"},{id:"h716",level:3,char:"怪",eumhun:"괴이할 괴"},{id:"h717",level:3,char:"菊",eumhun:"국화 국"},
  {id:"h718",level:3,char:"群",eumhun:"무리 군"},{id:"h719",level:3,char:"屈",eumhun:"굽을 굴"},{id:"h720",level:3,char:"歸",eumhun:"돌아갈 귀"},
  {id:"h721",level:3,char:"龜",eumhun:"거북 귀"},{id:"h722",level:3,char:"克",eumhun:"이길 극"},{id:"h723",level:3,char:"勤",eumhun:"부지런할 근"},
  {id:"h724",level:3,char:"琴",eumhun:"거문고 금"},{id:"h725",level:3,char:"禽",eumhun:"날짐승 금"},{id:"h726",level:3,char:"及",eumhun:"미칠 급"},
  {id:"h727",level:3,char:"肯",eumhun:"즐길 긍"},{id:"h728",level:3,char:"奇",eumhun:"기이할 기"},{id:"h729",level:3,char:"欺",eumhun:"속일 기"},
  {id:"h730",level:3,char:"棄",eumhun:"버릴 기"},{id:"h731",level:3,char:"緊",eumhun:"긴요할 긴"},{id:"h732",level:3,char:"裸",eumhun:"벗을 라"},
  {id:"h733",level:3,char:"爛",eumhun:"빛날 란"},{id:"h734",level:3,char:"嵐",eumhun:"남기 람"},{id:"h735",level:3,char:"浪",eumhun:"물결 랑"},
  {id:"h736",level:3,char:"糧",eumhun:"양식 량"},{id:"h737",level:3,char:"廬",eumhun:"오두막 려"},{id:"h738",level:3,char:"麗",eumhun:"고울 려"},
  {id:"h739",level:3,char:"戀",eumhun:"그리울 련"},{id:"h740",level:3,char:"蓮",eumhun:"연꽃 련"},{id:"h741",level:3,char:"烈",eumhun:"매울 렬"},
  {id:"h742",level:3,char:"獵",eumhun:"사냥 렵"},{id:"h743",level:3,char:"靈",eumhun:"신령 령"},{id:"h744",level:3,char:"鈴",eumhun:"방울 령"},
  {id:"h745",level:3,char:"路",eumhun:"길 로"},{id:"h746",level:3,char:"露",eumhun:"이슬 로"},{id:"h747",level:3,char:"爐",eumhun:"화로 로"},
  {id:"h748",level:3,char:"錄",eumhun:"기록할 록"},{id:"h749",level:3,char:"弄",eumhun:"희롱할 롱"},{id:"h750",level:3,char:"拉",eumhun:"꺾을 랍"},
  {id:"h751",level:3,char:"賴",eumhun:"힘입을 뢰"},{id:"h752",level:3,char:"漏",eumhun:"샐 루"},{id:"h753",level:3,char:"陵",eumhun:"능 릉"},
  {id:"h754",level:3,char:"梨",eumhun:"배나무 리"},{id:"h755",level:3,char:"裏",eumhun:"속 리"},{id:"h756",level:3,char:"隣",eumhun:"이웃 린"},
  {id:"h757",level:3,char:"臨",eumhun:"임할 림"},{id:"h758",level:3,char:"磨",eumhun:"갈 마"},{id:"h759",level:3,char:"幕",eumhun:"장막 막"},
  {id:"h760",level:3,char:"慢",eumhun:"게으를 만"},{id:"h761",level:3,char:"脈",eumhun:"맥 맥"},{id:"h762",level:3,char:"猛",eumhun:"사나울 맹"},
  {id:"h763",level:3,char:"盟",eumhun:"맹세 맹"},{id:"h764",level:3,char:"免",eumhun:"면할 면"},{id:"h765",level:3,char:"冥",eumhun:"어두울 명"},
  {id:"h766",level:3,char:"謀",eumhun:"꾀 모"},{id:"h767",level:3,char:"暮",eumhun:"저물 모"},{id:"h768",level:3,char:"墓",eumhun:"무덤 묘"},
  {id:"h769",level:3,char:"妙",eumhun:"묘할 묘"},{id:"h770",level:3,char:"茂",eumhun:"무성할 무"},{id:"h771",level:3,char:"武",eumhun:"굳셀 무"},
  {id:"h772",level:3,char:"默",eumhun:"잠잠할 묵"},{id:"h773",level:3,char:"微",eumhun:"작을 미"},{id:"h774",level:3,char:"迷",eumhun:"헤맬 미"},
  {id:"h775",level:3,char:"薄",eumhun:"엷을 박"},{id:"h776",level:3,char:"迫",eumhun:"핍박할 박"},{id:"h777",level:3,char:"博",eumhun:"넓을 박"},
  {id:"h778",level:3,char:"飯",eumhun:"밥 반"},{id:"h779",level:3,char:"伐",eumhun:"칠 벌"},{id:"h780",level:3,char:"範",eumhun:"법 범"},
  {id:"h781",level:3,char:"碧",eumhun:"푸를 벽"},{id:"h782",level:3,char:"壁",eumhun:"벽 벽"},{id:"h783",level:3,char:"弁",eumhun:"고깔 변"},
  {id:"h784",level:3,char:"補",eumhun:"기울 보"},{id:"h785",level:3,char:"普",eumhun:"넓을 보"},{id:"h786",level:3,char:"伏",eumhun:"엎드릴 복"},
  {id:"h787",level:3,char:"腹",eumhun:"배 복"},{id:"h788",level:3,char:"封",eumhun:"봉할 봉"},{id:"h789",level:3,char:"鳳",eumhun:"봉황새 봉"},
  {id:"h790",level:3,char:"否",eumhun:"아닐 부"},{id:"h791",level:3,char:"賦",eumhun:"세 부"},{id:"h792",level:3,char:"拂",eumhun:"떨칠 불"},
  {id:"h793",level:3,char:"崩",eumhun:"무너질 붕"},{id:"h794",level:3,char:"悲",eumhun:"슬플 비"},{id:"h795",level:3,char:"飛",eumhun:"날 비"},
  {id:"h796",level:3,char:"貧",eumhun:"가난할 빈"},{id:"h797",level:3,char:"賓",eumhun:"손 빈"},{id:"h798",level:3,char:"辭",eumhun:"말씀 사"},
  {id:"h799",level:3,char:"沙",eumhun:"모래 사"},{id:"h800",level:3,char:"捨",eumhun:"버릴 사"},
  {id:"h801",level:3,char:"削",eumhun:"깎을 삭"},{id:"h802",level:3,char:"索",eumhun:"찾을 색"},{id:"h803",level:3,char:"牲",eumhun:"희생 생"},
  {id:"h804",level:3,char:"緖",eumhun:"실마리 서"},{id:"h805",level:3,char:"析",eumhun:"쪼갤 석"},{id:"h806",level:3,char:"惜",eumhun:"아낄 석"},
  {id:"h807",level:3,char:"宣",eumhun:"베풀 선"},{id:"h808",level:3,char:"設",eumhun:"베풀 설"},{id:"h809",level:3,char:"涉",eumhun:"건널 섭"},
  {id:"h810",level:3,char:"歲",eumhun:"해 세"},{id:"h811",level:3,char:"昭",eumhun:"밝을 소"},{id:"h812",level:3,char:"蔬",eumhun:"나물 소"},
  {id:"h813",level:3,char:"續",eumhun:"이을 속"},{id:"h814",level:3,char:"率",eumhun:"거느릴 솔"},{id:"h815",level:3,char:"衰",eumhun:"쇠할 쇠"},
  {id:"h816",level:3,char:"秀",eumhun:"빼어날 수"},{id:"h817",level:3,char:"樹",eumhun:"나무 수"},{id:"h818",level:3,char:"輸",eumhun:"보낼 수"},
  {id:"h819",level:3,char:"隨",eumhun:"따를 수"},{id:"h820",level:3,char:"須",eumhun:"모름지기 수"},{id:"h821",level:3,char:"醇",eumhun:"순박할 순"},
  {id:"h822",level:3,char:"循",eumhun:"돌 순"},{id:"h823",level:3,char:"承",eumhun:"이을 승"},{id:"h824",level:3,char:"試",eumhun:"시험할 시"},
  {id:"h825",level:3,char:"侍",eumhun:"모실 시"},{id:"h826",level:3,char:"視",eumhun:"볼 시"},{id:"h827",level:3,char:"恃",eumhun:"믿을 시"},
  {id:"h828",level:3,char:"辛",eumhun:"매울 신"},{id:"h829",level:3,char:"審",eumhun:"살필 심"},{id:"h830",level:3,char:"尋",eumhun:"찾을 심"},
  {id:"h831",level:3,char:"嶽",eumhun:"큰산 악"},{id:"h832",level:3,char:"惡",eumhun:"악할 악"},{id:"h833",level:3,char:"巖",eumhun:"바위 암"},
  {id:"h834",level:3,char:"壓",eumhun:"누를 압"},{id:"h835",level:3,char:"仰",eumhun:"우러를 앙"},{id:"h836",level:3,char:"哀",eumhun:"슬플 애"},
  {id:"h837",level:3,char:"額",eumhun:"이마 액"},{id:"h838",level:3,char:"陽",eumhun:"별 양"},{id:"h839",level:3,char:"讓",eumhun:"사양할 양"},
  {id:"h840",level:3,char:"嚴",eumhun:"엄할 엄"},{id:"h841",level:3,char:"凝",eumhun:"엉길 응"},{id:"h842",level:3,char:"義",eumhun:"옳을 의"},
  {id:"h843",level:3,char:"宜",eumhun:"마땅할 의"},{id:"h844",level:3,char:"疑",eumhun:"의심할 의"},{id:"h845",level:3,char:"仁",eumhun:"어질 인"},
  {id:"h846",level:3,char:"刃",eumhun:"칼날 인"},{id:"h847",level:3,char:"磁",eumhun:"자석 자"},{id:"h848",level:3,char:"殘",eumhun:"남을 잔"},
  {id:"h849",level:3,char:"暫",eumhun:"잠깐 잠"},{id:"h850",level:3,char:"葬",eumhun:"장사지낼 장"},
  {id:"h851",level:3,char:"壯",eumhun:"씩씩할 장"},{id:"h852",level:3,char:"抵",eumhun:"막을 저"},{id:"h853",level:3,char:"赤",eumhun:"붉을 적"},
  {id:"h854",level:3,char:"征",eumhun:"칠 정"},{id:"h855",level:3,char:"竊",eumhun:"훔칠 절"},{id:"h856",level:3,char:"折",eumhun:"꺾을 절"},
  {id:"h857",level:3,char:"鳥",eumhun:"새 조"},{id:"h858",level:3,char:"彫",eumhun:"새길 조"},{id:"h859",level:3,char:"措",eumhun:"둘 조"},
  {id:"h860",level:3,char:"拙",eumhun:"서툴 졸"},{id:"h861",level:3,char:"悽",eumhun:"처량할 처"},{id:"h862",level:3,char:"淸",eumhun:"맑을 청"},
  {id:"h863",level:3,char:"超",eumhun:"뛰어넘을 초"},{id:"h864",level:3,char:"促",eumhun:"재촉할 촉"},{id:"h865",level:3,char:"追",eumhun:"쫓을 추"},
  {id:"h866",level:3,char:"醜",eumhun:"추할 추"},{id:"h867",level:3,char:"充",eumhun:"채울 충"},{id:"h868",level:3,char:"忠",eumhun:"충성 충"},
  {id:"h869",level:3,char:"取",eumhun:"가질 취"},{id:"h870",level:3,char:"臭",eumhun:"냄새 취"},{id:"h871",level:3,char:"侵",eumhun:"침노할 침"},
  {id:"h872",level:3,char:"稱",eumhun:"일컬을 칭"},{id:"h873",level:3,char:"快",eumhun:"쾌할 쾌"},{id:"h874",level:3,char:"脫",eumhun:"벗을 탈"},
  {id:"h875",level:3,char:"探",eumhun:"찾을 탐"},{id:"h876",level:3,char:"貪",eumhun:"탐낼 탐"},{id:"h877",level:3,char:"湯",eumhun:"끓을 탕"},
  {id:"h878",level:3,char:"鬪",eumhun:"싸울 투"},{id:"h879",level:3,char:"派",eumhun:"갈래 파"},{id:"h880",level:3,char:"罷",eumhun:"마칠 파"},
  {id:"h881",level:3,char:"片",eumhun:"조각 편"},{id:"h882",level:3,char:"廢",eumhun:"폐할 폐"},{id:"h883",level:3,char:"抱",eumhun:"안을 포"},
  {id:"h884",level:3,char:"暴",eumhun:"사나울 폭"},{id:"h885",level:3,char:"豊",eumhun:"풍성할 풍"},{id:"h886",level:3,char:"彼",eumhun:"저 피"},
  {id:"h887",level:3,char:"疲",eumhun:"피로할 피"},{id:"h888",level:3,char:"逼",eumhun:"핍박할 핍"},{id:"h889",level:3,char:"恨",eumhun:"한할 한"},
  {id:"h890",level:3,char:"抗",eumhun:"겨룰 항"},{id:"h891",level:3,char:"昏",eumhun:"어두울 혼"},{id:"h892",level:3,char:"洪",eumhun:"넓을 홍"},
  {id:"h893",level:3,char:"禍",eumhun:"재앙 화"},{id:"h894",level:3,char:"皇",eumhun:"임금 황"},{id:"h895",level:3,char:"黃",eumhun:"누를 황"},
  {id:"h896",level:3,char:"揮",eumhun:"휘두를 휘"},{id:"h897",level:3,char:"凶",eumhun:"흉할 흉"},{id:"h898",level:3,char:"喜",eumhun:"기쁠 희"},

  // ===== 2급 (대표 200자) =====
  {id:"h899",level:2,char:"佳",eumhun:"아름다울 가"},{id:"h900",level:2,char:"枷",eumhun:"칼 가"},
  {id:"h901",level:2,char:"桀",eumhun:"홰 걸"},{id:"h902",level:2,char:"肝",eumhun:"간 간"},{id:"h903",level:2,char:"轎",eumhun:"가마 교"},
  {id:"h904",level:2,char:"曲",eumhun:"굽을 곡"},{id:"h905",level:2,char:"棺",eumhun:"널 관"},{id:"h906",level:2,char:"郭",eumhun:"성곽 곽"},
  {id:"h907",level:2,char:"矯",eumhun:"바로잡을 교"},{id:"h908",level:2,char:"鞠",eumhun:"국화 국"},{id:"h909",level:2,char:"窟",eumhun:"굴 굴"},
  {id:"h910",level:2,char:"穹",eumhun:"하늘 궁"},{id:"h911",level:2,char:"倦",eumhun:"게으를 권"},{id:"h912",level:2,char:"厥",eumhun:"그 궐"},
  {id:"h913",level:2,char:"跪",eumhun:"꿇을 궤"},{id:"h914",level:2,char:"蹇",eumhun:"절름발이 건"},{id:"h915",level:2,char:"僅",eumhun:"겨우 근"},
  {id:"h916",level:2,char:"那",eumhun:"어찌 나"},{id:"h917",level:2,char:"諾",eumhun:"허락할 낙"},{id:"h918",level:2,char:"捺",eumhun:"누를 날"},
  {id:"h919",level:2,char:"乃",eumhun:"이에 내"},{id:"h920",level:2,char:"念",eumhun:"생각 념"},{id:"h921",level:2,char:"捏",eumhun:"쥘 날"},
  {id:"h922",level:2,char:"卵",eumhun:"알 란"},{id:"h923",level:2,char:"覽",eumhun:"볼 람"},{id:"h924",level:2,char:"藍",eumhun:"쪽 람"},
  {id:"h925",level:2,char:"朗",eumhun:"밝을 랑"},{id:"h926",level:2,char:"憐",eumhun:"불쌍히여길 련"},{id:"h927",level:2,char:"廉",eumhun:"청렴할 렴"},
  {id:"h928",level:2,char:"燐",eumhun:"도깨비불 린"},{id:"h929",level:2,char:"鱗",eumhun:"비늘 린"},{id:"h930",level:2,char:"笠",eumhun:"삿갓 립"},
  {id:"h931",level:2,char:"忘",eumhun:"잊을 망"},{id:"h932",level:2,char:"昧",eumhun:"어두울 매"},{id:"h933",level:2,char:"邁",eumhun:"나아갈 매"},
  {id:"h934",level:2,char:"眸",eumhun:"눈동자 모"},{id:"h935",level:2,char:"冒",eumhun:"무릅쓸 모"},{id:"h936",level:2,char:"沒",eumhun:"빠질 몰"},
  {id:"h937",level:2,char:"蒙",eumhun:"어두울 몽"},{id:"h938",level:2,char:"撫",eumhun:"어루만질 무"},{id:"h939",level:2,char:"縛",eumhun:"묶을 박"},
  {id:"h940",level:2,char:"泊",eumhun:"묵을 박"},{id:"h941",level:2,char:"搬",eumhun:"옮길 반"},{id:"h942",level:2,char:"斑",eumhun:"아롱질 반"},
  {id:"h943",level:2,char:"排",eumhun:"밀칠 배"},{id:"h944",level:2,char:"培",eumhun:"북돋울 배"},{id:"h945",level:2,char:"白",eumhun:"흰 백"},
  {id:"h946",level:2,char:"繁",eumhun:"번성할 번"},{id:"h947",level:2,char:"帆",eumhun:"돛 범"},{id:"h948",level:2,char:"瓶",eumhun:"병 병"},
  {id:"h949",level:2,char:"潑",eumhun:"뿌릴 발"},{id:"h950",level:2,char:"剝",eumhun:"벗길 박"},{id:"h951",level:2,char:"陛",eumhun:"섬돌 폐"},
  {id:"h952",level:2,char:"寶",eumhun:"보배 보"},{id:"h953",level:2,char:"縫",eumhun:"꿰맬 봉"},{id:"h954",level:2,char:"鵬",eumhun:"붕새 붕"},
  {id:"h955",level:2,char:"妃",eumhun:"왕비 비"},{id:"h956",level:2,char:"砂",eumhun:"모래 사"},{id:"h957",level:2,char:"邪",eumhun:"간사할 사"},
  {id:"h958",level:2,char:"詐",eumhun:"속일 사"},{id:"h959",level:2,char:"蛇",eumhun:"뱀 사"},{id:"h960",level:2,char:"霜",eumhun:"서리 상"},
  {id:"h961",level:2,char:"塞",eumhun:"막힐 색"},{id:"h962",level:2,char:"索",eumhun:"찾을 색"},{id:"h963",level:2,char:"敍",eumhun:"베풀 서"},
  {id:"h964",level:2,char:"甥",eumhun:"생질 생"},{id:"h965",level:2,char:"逝",eumhun:"갈 서"},{id:"h966",level:2,char:"攝",eumhun:"잡을 섭"},
  {id:"h967",level:2,char:"疏",eumhun:"성길 소"},{id:"h968",level:2,char:"訴",eumhun:"하소연할 소"},{id:"h969",level:2,char:"笑",eumhun:"웃을 소"},
  {id:"h970",level:2,char:"俗",eumhun:"풍속 속"},{id:"h971",level:2,char:"遜",eumhun:"겸손할 손"},{id:"h972",level:2,char:"訟",eumhun:"송사할 송"},
  {id:"h973",level:2,char:"殊",eumhun:"다를 수"},{id:"h974",level:2,char:"收",eumhun:"거둘 수"},{id:"h975",level:2,char:"搜",eumhun:"찾을 수"},
  {id:"h976",level:2,char:"肅",eumhun:"엄숙할 숙"},{id:"h977",level:2,char:"膝",eumhun:"무릎 슬"},{id:"h978",level:2,char:"拾",eumhun:"주울 습"},
  {id:"h979",level:2,char:"矢",eumhun:"화살 시"},{id:"h980",level:2,char:"翅",eumhun:"날개 시"},{id:"h981",level:2,char:"辰",eumhun:"별 신"},
  {id:"h982",level:2,char:"殃",eumhun:"재앙 앙"},{id:"h983",level:2,char:"仰",eumhun:"우러를 앙"},{id:"h984",level:2,char:"抑",eumhun:"누를 억"},
  {id:"h985",level:2,char:"偃",eumhun:"누울 언"},{id:"h986",level:2,char:"焰",eumhun:"불꽃 염"},{id:"h987",level:2,char:"汚",eumhun:"더러울 오"},
  {id:"h988",level:2,char:"傲",eumhun:"거만할 오"},{id:"h989",level:2,char:"獄",eumhun:"감옥 옥"},{id:"h990",level:2,char:"翁",eumhun:"늙은이 옹"},
  {id:"h991",level:2,char:"渦",eumhun:"소용돌이 와"},{id:"h992",level:2,char:"謠",eumhun:"노래 요"},{id:"h993",level:2,char:"腰",eumhun:"허리 요"},
  {id:"h994",level:2,char:"愚",eumhun:"어리석을 우"},{id:"h995",level:2,char:"鬱",eumhun:"울창할 울"},{id:"h996",level:2,char:"怨",eumhun:"원망할 원"},
  {id:"h997",level:2,char:"閏",eumhun:"윤달 윤"},{id:"h998",level:2,char:"潤",eumhun:"윤택할 윤"},{id:"h999",level:2,char:"凜",eumhun:"찰 름"},
  {id:"h1000",level:2,char:"刺",eumhun:"찌를 자"},

  // ===== 1급 (대표 200자) =====
  {id:"h1001",level:1,char:"訝",eumhun:"의아할 아"},{id:"h1002",level:1,char:"謁",eumhun:"뵐 알"},{id:"h1003",level:1,char:"雁",eumhun:"기러기 안"},
  {id:"h1004",level:1,char:"斡",eumhun:"돌 알"},{id:"h1005",level:1,char:"庵",eumhun:"암자 암"},{id:"h1006",level:1,char:"鴨",eumhun:"오리 압"},
  {id:"h1007",level:1,char:"罌",eumhun:"항아리 앵"},{id:"h1008",level:1,char:"揶",eumhun:"야유할 야"},{id:"h1009",level:1,char:"惹",eumhun:"이끌 야"},
  {id:"h1010",level:1,char:"倻",eumhun:"가야 야"},{id:"h1011",level:1,char:"冶",eumhun:"불릴 야"},{id:"h1012",level:1,char:"爺",eumhun:"아비 야"},
  {id:"h1013",level:1,char:"若",eumhun:"같을 약"},{id:"h1014",level:1,char:"躍",eumhun:"뛸 약"},{id:"h1015",level:1,char:"壤",eumhun:"흙 양"},
  {id:"h1016",level:1,char:"樣",eumhun:"모양 양"},{id:"h1017",level:1,char:"瘍",eumhun:"종기 양"},{id:"h1018",level:1,char:"膺",eumhun:"가슴 응"},
  {id:"h1019",level:1,char:"馭",eumhun:"말부릴 어"},{id:"h1020",level:1,char:"嶼",eumhun:"섬 여"},{id:"h1021",level:1,char:"黎",eumhun:"검을 려"},
  {id:"h1022",level:1,char:"礪",eumhun:"숫돌 려"},{id:"h1023",level:1,char:"戾",eumhun:"어그러질 려"},{id:"h1024",level:1,char:"廬",eumhun:"오두막 려"},
  {id:"h1025",level:1,char:"濾",eumhun:"거를 려"},{id:"h1026",level:1,char:"澪",eumhun:"뱃길 령"},{id:"h1027",level:1,char:"醴",eumhun:"단술 례"},
  {id:"h1028",level:1,char:"弩",eumhun:"쇠뇌 노"},{id:"h1029",level:1,char:"碌",eumhun:"평범할 록"},{id:"h1030",level:1,char:"龍",eumhun:"용 룡"},
  {id:"h1031",level:1,char:"婁",eumhun:"별 루"},{id:"h1032",level:1,char:"瘻",eumhun:"누공 루"},{id:"h1033",level:1,char:"鏤",eumhun:"새길 루"},
  {id:"h1034",level:1,char:"縷",eumhun:"실 루"},{id:"h1035",level:1,char:"壘",eumhun:"진 루"},{id:"h1036",level:1,char:"僚",eumhun:"동료 료"},
  {id:"h1037",level:1,char:"燎",eumhun:"사를 료"},{id:"h1038",level:1,char:"遼",eumhun:"멀 료"},{id:"h1039",level:1,char:"聆",eumhun:"들을 령"},
  {id:"h1040",level:1,char:"瞭",eumhun:"밝을 료"},{id:"h1041",level:1,char:"旒",eumhun:"기술 류"},{id:"h1042",level:1,char:"倫",eumhun:"인륜 륜"},
  {id:"h1043",level:1,char:"淪",eumhun:"빠질 륜"},{id:"h1044",level:1,char:"輪",eumhun:"바퀴 륜"},{id:"h1045",level:1,char:"侶",eumhun:"짝 려"},
  {id:"h1046",level:1,char:"詭",eumhun:"속일 궤"},{id:"h1047",level:1,char:"揆",eumhun:"헤아릴 규"},{id:"h1048",level:1,char:"窺",eumhun:"엿볼 규"},
  {id:"h1049",level:1,char:"魁",eumhun:"으뜸 괴"},{id:"h1050",level:1,char:"軌",eumhun:"바퀴자국 궤"},{id:"h1051",level:1,char:"跪",eumhun:"꿇을 궤"},
  {id:"h1052",level:1,char:"簀",eumhun:"삿자리 책"},{id:"h1053",level:1,char:"策",eumhun:"꾀 책"},{id:"h1054",level:1,char:"擲",eumhun:"던질 척"},
  {id:"h1055",level:1,char:"薦",eumhun:"천거할 천"},{id:"h1056",level:1,char:"撤",eumhun:"걷을 철"},{id:"h1057",level:1,char:"綴",eumhun:"꿸 철"},
  {id:"h1058",level:1,char:"諦",eumhun:"진리 제"},{id:"h1059",level:1,char:"滯",eumhun:"막힐 체"},{id:"h1060",level:1,char:"逮",eumhun:"잡을 체"},
  {id:"h1061",level:1,char:"遞",eumhun:"갈릴 체"},{id:"h1062",level:1,char:"肖",eumhun:"닮을 초"},{id:"h1063",level:1,char:"楚",eumhun:"나라 초"},
  {id:"h1064",level:1,char:"樵",eumhun:"나무꾼 초"},{id:"h1065",level:1,char:"礁",eumhun:"암초 초"},{id:"h1066",level:1,char:"矗",eumhun:"우뚝 촉"},
  {id:"h1067",level:1,char:"囑",eumhun:"부탁할 촉"},{id:"h1068",level:1,char:"叢",eumhun:"떨기 총"},{id:"h1069",level:1,char:"塚",eumhun:"무덤 총"},
  {id:"h1070",level:1,char:"撮",eumhun:"잡을 촬"},{id:"h1071",level:1,char:"墜",eumhun:"떨어질 추"},{id:"h1072",level:1,char:"錐",eumhun:"송곳 추"},
  {id:"h1073",level:1,char:"抽",eumhun:"뽑을 추"},{id:"h1074",level:1,char:"樞",eumhun:"지도리 추"},{id:"h1075",level:1,char:"蹴",eumhun:"찰 축"},
  {id:"h1076",level:1,char:"衝",eumhun:"찌를 충"},{id:"h1077",level:1,char:"娶",eumhun:"장가들 취"},{id:"h1078",level:1,char:"翠",eumhun:"물총새 취"},
  {id:"h1079",level:1,char:"嗤",eumhun:"비웃을 치"},{id:"h1080",level:1,char:"癡",eumhun:"어리석을 치"},{id:"h1081",level:1,char:"緻",eumhun:"빽빽할 치"},
  {id:"h1082",level:1,char:"砧",eumhun:"다듬잇돌 침"},{id:"h1083",level:1,char:"寢",eumhun:"잠잘 침"},{id:"h1084",level:1,char:"駝",eumhun:"낙타 타"},
  {id:"h1085",level:1,char:"惰",eumhun:"게으를 타"},{id:"h1086",level:1,char:"歎",eumhun:"탄식할 탄"},{id:"h1087",level:1,char:"炭",eumhun:"숯 탄"},
  {id:"h1088",level:1,char:"奪",eumhun:"빼앗을 탈"},{id:"h1089",level:1,char:"眈",eumhun:"노려볼 탐"},{id:"h1090",level:1,char:"慟",eumhun:"통곡할 통"},
  {id:"h1091",level:1,char:"閭",eumhun:"마을 려"},{id:"h1092",level:1,char:"褪",eumhun:"빛바랠 퇴"},{id:"h1093",level:1,char:"鬪",eumhun:"싸울 투"},
  {id:"h1094",level:1,char:"褒",eumhun:"칭찬할 포"},{id:"h1095",level:1,char:"匍",eumhun:"기어갈 포"},{id:"h1096",level:1,char:"飽",eumhun:"배부를 포"},
  {id:"h1097",level:1,char:"幅",eumhun:"폭 폭"},{id:"h1098",level:1,char:"瀑",eumhun:"폭포 폭"},{id:"h1099",level:1,char:"諷",eumhun:"풍자할 풍"},
  {id:"h1100",level:1,char:"彼",eumhun:"저 피"},{id:"h1101",level:1,char:"披",eumhun:"헤칠 피"},{id:"h1102",level:1,char:"鶴",eumhun:"학 학"},
  {id:"h1103",level:1,char:"翰",eumhun:"편지 한"},{id:"h1104",level:1,char:"邯",eumhun:"땅이름 한"},{id:"h1105",level:1,char:"劾",eumhun:"탄핵할 핵"},
  {id:"h1106",level:1,char:"嚮",eumhun:"향할 향"},{id:"h1107",level:1,char:"墟",eumhun:"빈터 허"},{id:"h1108",level:1,char:"峴",eumhun:"고개 현"},
  {id:"h1109",level:1,char:"弦",eumhun:"활시위 현"},{id:"h1110",level:1,char:"蛤",eumhun:"조개 합"},{id:"h1111",level:1,char:"沆",eumhun:"넓은물 항"},
  {id:"h1112",level:1,char:"嚎",eumhun:"울부짖을 호"},{id:"h1113",level:1,char:"濠",eumhun:"해자 호"},{id:"h1114",level:1,char:"婚",eumhun:"혼인할 혼"},
  {id:"h1115",level:1,char:"渾",eumhun:"흐릴 혼"},{id:"h1116",level:1,char:"弘",eumhun:"클 홍"},{id:"h1117",level:1,char:"鴻",eumhun:"기러기 홍"},
  {id:"h1118",level:1,char:"劃",eumhun:"그을 획"},{id:"h1119",level:1,char:"宦",eumhun:"벼슬 환"},{id:"h1120",level:1,char:"煥",eumhun:"빛날 환"},
  {id:"h1121",level:1,char:"彙",eumhun:"무리 휘"},{id:"h1122",level:1,char:"欣",eumhun:"기쁠 흔"},{id:"h1123",level:1,char:"屹",eumhun:"높이솟을 흘"},
  {id:"h1124",level:1,char:"僖",eumhun:"즐거울 희"},{id:"h1125",level:1,char:"犧",eumhun:"희생 희"},{id:"h1126",level:1,char:"羲",eumhun:"복희씨 희"}
];

// level label map
const LEVEL_LABELS = {8:"8급",7:"7급",6:"6급",5:"5급",4:"4급",3:"3급",2:"2급",1:"1급"};

function getByLevels(levels) {
  return HANJA_DATA.filter(h => levels.includes(h.level));
}
